---
title: "The Recrudescence of Reproductive Justice"
author: "Emma Huizenga"
tag: "Reproductive Justice"
summary: "Increases in Public Contempt Doesn't Yeild Much Success"
date: "October 31 2023"
figure_path: midterm_project_plot.pdf
output: 
  pdf_document:
    template: econ_template.tex
---

In a nation characterized by an enduring struggle for civil liberties, a powerful social movement is once again making waves. The United States, a country often hailed as the land of opportunity, finds itself at the epicenter of a profound and ongoing debate—reproductive justice. As the nation grapples with complex issues surrounding women's health, bodily autonomy, and equal access to healthcare, a resurgence of reproductive justice protests has erupted; the fight for reproductive justice is not just a women's issue—it is a human rights issue. 

Figure A illustrates a substantial increase in reproductive justice protests, notably peaking in mid-2022 following the overturn of Roe v. Wade by the conservative Supreme Court majority. Prior to 2022, a notable surge in protests occurred in late 2021, coinciding with the U.S. Supreme Court's decision to review a Mississippi law aiming to restrict abortions after 15 weeks, known as "Dobbs v. Jackson Women's Health Organization." This case garnered significant attention, serving as a focal point for the reproductive justice movement.

In Figure B, we focus on reproductive justice protests led by left-wing/anti-Trump organizations, highlighting 2020 and 2023 as the years with the highest protest frequency. The spikes in 2020 and 2023 could be primarily attributed to the transformative effects of the COVID-19 pandemic, which profoundly impacted healthcare access, and the momentum generated by the #MeToo or BLM movement. These years saw reproductive justice protests intersect with these significant societal shifts. Additionally, these spikes also reflect the resounding public disapproval following the overturning of Roe v. Wade in 2023. While changes in reproductive rights policies, influential elections, legislative actions, and broader social justice movements like Black Lives Matter played crucial roles, it was the confluence of these factors that fueled the surge in activism during these pivotal years.

In the context of Michigan, Figure C provides insights into protest frequencies across different cities, with each dot representing the average protest size. Notably, cities where protests boasted an average attendance of 1000 participants or more are explicitly labeled. A conspicuous pattern emerges, with a concentration of such cities appearing around June 24th, a date closely tied to the landmark Roe v. Wade decision reversal. It's worth highlighting that some of the most substantial protests occurred prior to this pivotal date, underscoring the profound public dissent in anticipation of the Dobbs case's predicted outcome. 

These findings suggest that despite America's perception as a representative democracy, the apparent violations of human rights in various states may not consistently align with the public agenda, especially after the overturn of Roe v. Wade. Although there is public discontent and disapproval of these policies, protests may not always translate into effective mechanisms for voicing concerns, potentially leading to limited success in achieving political and legal changes.














