---
title: "final"
author: "Huizenga"
date: "2023-11-20"
output: pdf_document
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


```{r}
library(ggplot2)
library(RColorBrewer)
library(scales)
library(grid)
library(ggtext)
library(patchwork)

theme_econ_andy <- function() {
  # Generate the colors for the chart procedurally with RColorBrewer
  palette <- brewer.pal("Greys", n=9)
  color.background = palette[1]
  color.grid.minor = palette[2]
  color.grid.major = palette[3]
  color.axis.text = palette[8] #[6]
  color.axis.title = palette[8]
  color.legend.title = palette[8]
  color.title = palette[9]
  
  grey_8 <- palette[8]
  
  # Begin construction of chart
  theme_bw(base_size=9)  + 
    
    theme(panel.background=element_rect(fill=color.background, color=color.background))  + 
    theme(plot.background=element_rect(fill=color.background, color=color.background))  + 
    theme(panel.border=element_rect(color=color.background))  + 
    
    # Format the grid
    theme(panel.grid.major.y = element_line(color=palette[6], size=.04))  + 
    ## NOTE: Some Economist figures don't include vertical grid lines.
    # To remove them, add + theme(panel.grid.major.x =  element_blank()) to
    # your ggplot plot
    theme(panel.grid.major.x = element_line(color=palette[6], size=.04))  + 
    theme(panel.grid.minor=element_line(color=color.grid.minor, size=.03))  + 
    theme(panel.grid.minor.y=element_blank())  + 
    theme(axis.ticks.y =element_blank())  + 
    theme(axis.ticks.x =element_line(color="black", size=.11))  +
    theme(axis.line.x = element_line(color="black", size=.11))  +
    # remove distance between plotting area and axis:
    theme(panel.border = element_blank()) +
    
    # Format the legend
    theme(legend.background = element_rect(fill=color.background))  + 
    theme(legend.key = element_rect(fill=color.background))  + 
    theme(legend.text = element_text(size=7,color=color.legend.title))  + 
    theme(legend.title = element_text(size=8,color=color.legend.title))  + 
    
    # Set title and axis labels, and format these and tick marks
    theme(plot.title=element_markdown(color=color.title, size=10, vjust=1.25))  + 
    theme(axis.text.x=element_markdown(size=7,color=color.axis.text))  + 
    theme(axis.text.y=element_markdown(size=7,color=color.axis.text))  + 
    theme(axis.title.x=element_markdown(size=8,color=color.axis.title, vjust=0))  + 
    theme(axis.title.y=element_markdown(size=8,color=color.axis.title, vjust=1.25))  + 
    
    # facet stuff
    theme(strip.text = element_text(size=8,color=color.axis.text)) +
    theme(strip.background = element_rect(colour = color.background, 
                                          fill = palette[2], size = 0.5)) +
    # Title fonts
    #theme(plot.title=element_text(family="OpenSans-CondensedBold", margin=margin(b=15)))  + 
    #theme(plot.subtitle=element_text(family="OpenSans-CondensedLightItalic"))  + 
    
    # Plot margins
    theme(plot.margin = unit(c(0.35, 0.2, 0.3, 0.35), "cm"))
}

# Set the theme as the default, so it'll get added to all your figures.
theme_set(theme_econ_andy())
```



```{r}
TRIP <- read.csv("replication_data.tab", sep="\t")
```




```{r}

library(dplyr)
library(countrycode)
library(maps)
library(ggplot2)
library(haven)

world_data <- map_data("world") %>%
  fortify() %>%
  mutate(country_text_id = countryname(region, destination = "iso3c")) 

```

```{r}
world_data2021 <- world_data %>% 
  mutate(year=2021) %>%
  full_join(subset(TRIP, year==2021), by=c("country_text_id", "year"))


p1 <- ggplot(world_data2021, aes(x = long, y = lat, group = group, fill = as.factor(ind_crim))) +
  geom_polygon(color="white", size=.1) +
  theme_void() +
  scale_fill_viridis_d(end=0.8, direction = 1,  na.value = "grey80", name="",
                     labels = c("No Indirect Criminalization", "Indirect Criminalization is Present", "No data")) +
  theme(legend.position = "bottom")  +
  coord_fixed(ratio = 1.25)  +
  labs(title = "2021 Data Reveals Overlooked Challenges to Trans Rights") 


```










```{r}

aggregated_data2021 <- world_data2021 %>%
  group_by(country_name) %>%
  summarize(median_religiosity = median(religiosity_percent),
            median_trip_score = median(trip_score),
            median_trip_percent = median(trip_percent), 
            median_adp = median(adp_general))

#aggregated_data2021 <- aggregated_data2021 %>% 
#  mutate(label = ifelse(median_trip_percent >= .75, as.character(country_name), NA), 
#         fill = ifelse(median_trip_percent >= .75, "safe", "not safe")) %>%
#  mutate(fill = as.factor(fill)) 
  #mutate(label2 = ifelse(median_adp = 1, as.character(country_name), NA), 
       #  fill2 = ifelse(median_adp = 1, "safe", "not safe")) %>% 
 # mutate(fill2 = as.factor(fill2))

aggregated_data2021 <- aggregated_data2021 %>% 
  filter(!is.na(country_name))

aggregated_data2021$country_name_label <- NA
aggregated_data2021[aggregated_data2021$country_name == "United States of America", "country_name_label"] <- "United States of America"
aggregated_data2021[aggregated_data2021$country_name == "Germany", "country_name_label"] <- "Germany"
aggregated_data2021[aggregated_data2021$country_name == "North Korea", "country_name_label"] <- "North Korea"
aggregated_data2021[aggregated_data2021$country_name == "Czechia", "country_name_label"] <- "Czechia"
aggregated_data2021[aggregated_data2021$country_name == "Uruguay", "country_name_label"] <- "Uruguay"
aggregated_data2021[aggregated_data2021$country_name == "United Kingdom", "country_name_label"] <- "United Kingdom"
aggregated_data2021[aggregated_data2021$country_name == "Belgium", "country_name_label"] <- "Belgium"
aggregated_data2021[aggregated_data2021$country_name == "France", "country_name_label"] <- "France"
aggregated_data2021[aggregated_data2021$country_name == "Pakistan", "country_name_label"] <- "Pakistan"

```


```{r}
p2 <- ggplot(aggregated_data2021, aes(x = median_religiosity, 
                                y = median_trip_score, 
                                label = country_name_label, 
                                text = country_name_label,
                                #alpha = fill, 
                                color = country_name_label
                                 )) +
      geom_point(alpha = .75) +
      labs(title = "Reassessing the Influence of \n Religiosity on Trans Rights",
            x = "Religiosity Percent",
            y = "TRIP Score",
            color = "Country") +
      theme_classic() +
      theme(legend.position = "none") +
      ggrepel::geom_text_repel() +
      theme(plot.title = element_text(size=9))


```




```{r}

top_countries <- TRIP %>% 
  select(country_name, lgb_score, wb_gdppc, trip_score ) %>% 
  group_by(country_name) %>% 
  summarize(mean_gdp = mean(wb_gdppc), 
            mean_lgbscore = mean(lgb_score, na.rm = TRUE), 
            mean_tripscore = mean(trip_score, na.rm = TRUE)) %>% 
  arrange(desc(mean_gdp)) %>%
  slice_head(n = 5)

```


```{r}
library(ggtext)
```


```{r}

top_countries_long <- top_countries %>% 
  pivot_longer(cols=c(mean_lgbscore, mean_tripscore),
               names_to="score_type",
               values_to="score")

p3 <- ggplot(top_countries_long, aes(
    x = reorder(country_name, mean_gdp), 
    fill = score_type, 
    y = score)) +
  geom_col(aes(y = score), position = "dodge", width = 0.4, color = "black") +
  labs(x = "", 
       y = "Score",
       title = "<span style = 'color: #7380FF'> *TRIP* </span> and <span style = 'color:#FF7373'> *LGB* </span> Scores",
       fill = "Score") +
  theme_classic() +
  theme(legend.position = "none", 
        legend.title = element_blank()) +
  coord_flip() +
  scale_fill_manual(labels = c("LGB", "TRIP"),
                    values = c("#FF7373", "#7380FF")) +  
   theme(plot.title = element_markdown()) 
  
 
 
```



```{r}

combo_plot <- p1 / (p2 | p3) + plot_layout(heights = c(3, 2))


combo_plot <- combo_plot +
  plot_annotation(
    caption = "Data From Trans Rights Indicator Project",
    title = "A Comprehensive Look at the Diverse Landscape of Global Trans Rights"
  )


```




```{r}
ggsave(combo_plot, file="final_plot.pdf", height=7)
```

