--- 
title: "The Unique Challenges of Trans Identity"
author: "Emma Huizenga"
tag: "Trans Rights"
summary: "Understanding the Varied Realities of Transgender Lives Worldwide"
date: "December 11 2023"
figure_path: final_plot.pdf
output: 
  pdf_document:
    template: econ_template.tex
---

A resurgence of backlash is posing a renewed threat to the rights of transgender individuals globally. In the United States, legislatures in various states have introduced numerous anti-trans bills, aiming at diminishing rights such as access to gender-affirming healthcare and legal gender recognition. Concurrently, nations like Hungary and Russia have enacted and broadened anti-LGBT propaganda laws, intensifying restrictions on the freedoms of expression for gender identity minorities. Examining and comprehending the restrictive state of transgender individuals may be trickier than anticipated, and circumventing existing barriers to their rights involves looking at these constraints through various lenses.  

To gain a complete understanding of how trans people are affected, The Trans Rights Indicator Project has compiled a data set comprising 14 indicators. These indicators assess the legal landscape for transgender individuals across 173 countries from 2000 to 2021. The project aims to encapsulate the existence or absence of laws pertaining to criminalization, legal gender recognition, and anti-discrimination protections.

Many countries actively discriminate through their arbitrary application of laws unrelated to gender identity or expression to target transgender people. For example, security forces use laws concerning “public order,” “vagrancy,” “morality,” “decency,” and other vague offenses to indirectly criminalize trans individuals. The ambiguous implementations of laws, often used to suppress and criminalize individuals based on their identities, highlights the formidable challenges people face in asserting and expressing their identity. In a landscape where criminalization is prevalent, overcoming these obstacles within a system that disproportionately disadvantages certain groups may prove to be even more challenging than initially anticipated.

Furthermore, the authors of the Trans Indicator project created their own variable that presents a yearly score for each country to represent the total domestic legal rights available for transgender people. Possible scores range from 0 to 13, with higher scores indicating more rights. I wanted to evaluate the influence of religiosity for each country and their corresponding TRIP score to gauge a better understanding of how these variables may interact with each other. Outliers, prominent countries, as well as the maximum and minimum values are highlighted as a visual emphasis. Certain countries, like North Korea, may seem more expected in their stance, while others, such as Pakistan, present intriguing observations. With a high religiosity percent and a TRIP score of 11, Pakistan's case raises questions about the influence of religion on legal implications concerning trans rights. These nuances underscore the intricate nature of each country's dynamics and how they intersect with legal ramifications. 

Even among some of the wealthiest nations, the living conditions for their transgender residents may be substandard. The data set also incorporates LGB scores for each country, utilizing 11 indicators derived from ILGA World’s State-Sponsored Homophobia Report. The bar chart aims to examine the differences in the TRIP indicator capturing legal gender recognition and the rights countries offered to sexual orientation. The findings indicate that recognition and protection for LGB individuals may be more prevalent than trans gender people in more developed countries, with the notable exception of Qatar. This anomaly could be attributed to insufficient data regarding LGB laws in certain regions, or the possibility that in some cases protections for trans individuals do exist while LGB protections do not. Countries do not inherently treat sexual orientation and transgender rights equally, and conflating the two measures may misrepresent the actual domestic legal situation. It is important to distinguish this, as the blurring of these two aspects can lead to misconceptions about the actual level of protections for transgender individuals in a specific region.

The legal situation for transgender individuals is gradually improving, albeit at a modest pace. Acknowledging the inherent and somewhat implicit challenges faced by these minorities is crucial for rectifying and enhancing their legal standing. Understanding how specific characteristics of certain countries may impact minoritized identity status and recognizing the distinctions within sexual minorities holds the potential to improve trans minorities globally. 






